name: Notificações Agendadas

on:
  schedule:
    - cron: '* * * * *' # a cada 1 minuto
  workflow_dispatch:      # permite rodar manualmente também

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar endpoint de notificações agendadas
        run: |
          curl -X POST https://runa-phi.vercel.app/api/send-notifications