name: Build and Deploy

on:
  push:
    branches:
      - main  # ou 'master', dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short commit SHA
        id: get_sha
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create version.js file
        run: echo "window.APP_VERSION = \"${{ steps.get_sha.outputs.SHA }}\";" > version.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # ou outra pasta se tiver
          publish_branch: gh-pages